# Rpcd.core error codes
CORE_MISSING_COMPONENT = 1
CORE_MISSING_SERVICE = 2
CORE_CALL_SERVICE_ERROR = 3

# Rpcd.auth error codes
AUTH_PERMISSION_DENIED = 1
AUTH_CONFIG_ERROR = 2
AUTH_LDAP_ERROR = 3
AUTH_RADIUS_ERROR = 4
AUTH_INVALID_PARAMETER = 5

# Rpcd.acl error codes
ACL_PERMISSION_DENIED = 1
ACL_INVALID_LOGIN = 2
ACL_DB_ERROR = 3

# Rpcd.session error codes
SESSION_INVALID_ARG = 1
SESSION_INVALID_VERSION = 2
SESSION_NO_USER = 3
SESSION_DUPLICATE = 4
SESSION_INVALID_COOKIE = 5
SESSION_GEN_COOKIE_ERROR = 6
SESSION_BROKEN_REF = 7
SESSION_DIFFERENT_ADDRESS = 8

#Rpcd.audit error codes
ALERT_ALREADY_ACK = 1
ACK_FORBIDDEN = 2
API_PROBLEM = 3
DB_NO_CONNECTION = 4
