
TXT_FILES = nucentral.txt \
            intro.txt \
	    installation.txt \
	    authentication.txt \
	    adding-services.txt \
	    events.txt \
	    specs.txt \
	    ssl.txt \
	    cron.txt \
	    log.txt

include ../Makefile.common

