#!/usr/bin/env python
from sys import exit
from ufwi_rpcc_qt.application import create_ufwi_rpcd_application
from ufwi_ruleset.version import VERSION

def createOptions(parser):
    parser.add_option('--ruleset',
        help="Open the specified ruleset",
        type="str", default=None)
    parser.add_option('--template',
        help="Open the specified template",
        type="str", default=None)
    parser.add_option('--new',
        help="Create a new ruleset",
        action="store_true")

def main():
    app, client = create_ufwi_rpcd_application(
        name="ufwi-ruleset",
        resource="ufwi-ruleset.rcc",
        locale=":/nuface/locale/nuface",
        create_options=createOptions,
        release=VERSION,
    )

    from ufwi_rulesetqt.main_window import MainWindow
    window = MainWindow(app, client)
    window.load()
    window.show()
    return app.exec_()

if __name__ == "__main__":
    code = main()
    exit(code)

