allowed_types = """
    ufwi_conf.common.access_cfg.AccessConf
    ufwi_conf.common.antispam_cfg.AntispamConf
    ufwi_conf.common.auth_cert_cfg.AuthCertConf
    ufwi_conf.common.contact_cfg.ContactConf
    ufwi_conf.common.dhcpcfg.DHCPCfg
    ufwi_conf.common.dhcpcfg.DHCPRange
    ufwi_conf.common.ha_cfg.HAConf
    ufwi_conf.common.hostnamecfg.HostnameCfg
    ufwi_conf.common.httpout_cfg.HttpOutConf
    ufwi_conf.common.ids_ips_cfg.IdsIpsCfg
    ufwi_conf.common.id_store.PersistentID
    ufwi_conf.common.mail_cfg.MailConf
    ufwi_conf.common.netcfg.NetCfg
    ufwi_conf.common.netcfg_rw.NetCfgRW
    ufwi_conf.common.net_interfaces.Bonding
    ufwi_conf.common.net_interfaces.Ethernet
    ufwi_conf.common.net_interfaces.Interface
    ufwi_conf.common.net_interfaces.PointToPoint
    ufwi_conf.common.net_interfaces.Vlan
    ufwi_conf.common.net_interfaces.Vlanable
    ufwi_conf.common.net_objects.Net
    ufwi_conf.common.net_objects.Route
    ufwi_conf.common.net_objects_rw.NetRW
    ufwi_conf.common.net_objects_rw.RouteRW
    ufwi_conf.common.openvpn_cfg.OpenVpnConf
    ufwi_conf.common.resolvcfg.ResolvCfg
    ufwi_conf.common.site2site_cfg.Fingerprint
    ufwi_conf.common.site2site_cfg.Site2SiteCfg
    ufwi_conf.common.site2site_cfg.VPN
    ufwi_conf.common.snmpd_cfg.SnmpdConf
    ufwi_conf.common.squid_cfg.SquidConf
    ufwi_conf.common.update_cfg.UpdateCfg
    ufwi_conf.common.user_dir.base.AbstractAuth
    ufwi_conf.common.user_dir.base.AbstractOrg
    ufwi_conf.common.user_dir.base.AbstractUserdir
    ufwi_conf.common.user_dir.base.ADOrg
    ufwi_conf.common.user_dir.base.KerberosADAuth
    ufwi_conf.common.user_dir.base.KerberosAuth
    ufwi_conf.common.user_dir.base.LDAPOrg
    ufwi_conf.common.user_dir.base.NndOrg
    ufwi_conf.common.user_dir.base.NndDomain
    ufwi_conf.common.user_dir.base.NndServer
    ufwi_conf.common.user_dir.base.NuauthCfg
    ufwi_conf.common.user_dir.base.RadiusAuth
    ufwi_conf.common.user_dir.base.SameAsOrgAuth
    ufwi_conf.common.user_dir.base.NotConfiguredOrg
    ufwi_conf.common.user_dir.base.NotConfiguredAuth
    """.split()

