# -*- coding: utf-8 -*-
# Component error codes.

NUCONF_BACKEND = 1
NUCONF_ACCESS = 2
NUCONF_ANTIVIRUS = 3
NUCONF_EXIM = 4
NUCONF_HOSTNAME = 5
NUCONF_HOSTS = 6
NUCONF_NETWORK = 7
NUCONF_NUAUTH = 8
NUCONF_NUCONF = 9
NUCONF_OPENSWAN = 10
NUCONF_RESOLV = 11
NUCONF_SQUID = 12
NUCONF_STATUS = 13
NUCONF_SYSTEM = 14
NUCONF_TOOLS = 15
NUCONF_WINBIND = 16
NUCONF_BIND = 17
NUCONF_DHCP = 18
NUCONF_HAVP = 19
NUCONF_NTP = 20
NUCONF_NUAUTH_COMMAND = 21
NUCONF_OPENVPN = 22
NUCONF_SNMPD = 23
NUCONF_SQUIDGUARD = 24
NUCONF_SYSTEM_INFO = 25
NUCONF_UPDATE = 26
NUCONF_ANTISPAM = 27
NUCONF_IDS_IPS = 28
NUCONF_SITE2SITE = 29
NUCONF_CONTACT = 30
NUCONF_LICENSE = 31
NUCONF_HA = 32
NUCONF_SYSLOG_EXPORT = 33
